#!/usr/bin/env node
import fs from "node:fs"; import path from "node:path";
const dir=process.argv[2]; if(!dir){console.error("Usage: node validate-flow.mjs <iteration-directory>");process.exit(2)}
const errors=[]; const read=n=>fs.readFileSync(path.join(dir,n),"utf8"); let data; try{data=JSON.parse(read("task.json"))}catch(e){errors.push(`task.json invalid: ${e.message}`)}
const tasks=Array.isArray(data)?data:data?.tasks; const allowed=new Set(["pending","in_progress","passed","failed","blocked","skipped","inconclusive"]); const ids=new Set();
if(!Array.isArray(tasks)) errors.push("task.json must be an array or contain tasks array"); else for(const t of tasks){if(!t.taskId)errors.push("task missing taskId"); else if(ids.has(t.taskId))errors.push(`duplicate taskId: ${t.taskId}`); else ids.add(t.taskId); if(!allowed.has(t.status))errors.push(`${t.taskId}: invalid status`); for(const f of ["depends","evidence","databaseMigration","productionRelease"])if(!Array.isArray(t[f]))errors.push(`${t.taskId}: ${f} must be array`); if(["passed","failed"].includes(t.status)&&!t.evidence?.length)errors.push(`${t.taskId}: ${t.status} requires evidence`); if(["blocked","skipped"].includes(t.status)&&!t.reason)errors.push(`${t.taskId}: ${t.status} requires reason`); for(const d of t.depends??[])if(d!=="all"&&!ids.has(d)&&!tasks.some(x=>x.taskId===d))errors.push(`${t.taskId}: unknown dependency ${d}`)}
if(fs.existsSync(path.join(dir,"task.md"))&&Array.isArray(tasks)){const md=read("task.md"); for(const id of ids)if(!new RegExp(`\\b${id}\\b`).test(md))errors.push(`${id}: missing from task.md`); for(const id of (md.match(/\bT\d+\b/g)??[]))if(!ids.has(id))errors.push(`${id}: missing from task.json`)}
if(fs.existsSync(path.join(dir,"design.md"))&&Array.isArray(tasks)){const md=read("design.md"); for(const f of (md.match(/\bF-\d+\b/g)??[]))if(!tasks.some(t=>t.featureId===f))errors.push(`${f}: no task mapping`)}
if(errors.length){console.error(errors.join("\n"));process.exit(1)} console.log(`flow valid: ${tasks.length} tasks`);
